Lisätty forwaus Mastodonin host-metaan (mahtaako toimia..)
hacklab-fi/hacklab-website pull request #61
Opened 2024-01-30 18:58 UTC by vranki

2024-01-30 23:09 UTC, olmari requested changes

2024-01-30 23:09 UTC, olmari commented on mastodon-well-known-host-meta
> +  <Link rel="lrdd" template="https://some.hacklab.fi/.well-known/webfinger?resource={uri}" type="application/xrd+xml" />
According to https://gist.github.com/junosuarez/012755df0243ad17d942ddf26eb707a7#theory

> if we're ok using the same forwarding information for any account on the domain, we can ignore the resource query param and use a static json document as our response!

So this line should likely be: `<Link rel="lrdd" template="https://cool.example/.well-known/webfinger" type="application/xrd+xml" />`

2024-01-30 23:15 UTC, olmari commented
Yleistasolla tuolla sasmaisessa dokumentissä mainitaan myös lopuksi:

> gotchas + caveats
> this is like the basic email forwarding that some domain registrars offer - people can contact you at this address, but your outgoing mail will come from your actual email provider.
> 
> similarly, this method will let people search for your by your custom domain address, but your posts will appear to come from your home mastodon instance address.
> 
> if you really want the full custom domain experience, you'll have to get fancier, maybe even run your own mastodon instance - but that's outside the scope of this gist.
> 

Jotta ei tämä nyt kokonaisuudessaan vaikuta siltä että ihan matrixin kaltaiseen erotteluun päästään domainnimien kanssa vaikka tekis miten täydellistä linkkausta...

2024-02-04 17:04 UTC, closed without merging

2024-02-04 17:04 UTC, vranki commented
Github pages tulee vastaan ja tämä todnäk ei toimisi. Käytetään vaan some.hacklab.fi:tä.